### ISSUE TITLE
Running example does not yield example result

### ISSUE THREAD

**Issue by jakob1379** [peppelinux/django-admin-search-builder#2]
Hello there! I tried to clone the repo and run the example while creating a superuser I get the perfectly running blank page
![image](https://user-images.githubusercontent.com/17257805/138230789-69111a6b-2e61-4c80-acba-c698e8735bf2.png)

I'd love to use your implementation as it looks like the perfect tool for my problem!

**Comment by peppelinux** [comment]
yes, it works only in admin backend, for the adminmodel you configure with

**Comment by jakob1379** [comment]
Well that actually makes perfect sense! Thanks.

**Comment by peppelinux** [comment]
mind to put a start if you like this project!
and thank you
